source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView, LoginViewSession, \
    json_echo_view

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginViewSession.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset'),

]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api_v1.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

source/webapp/models.py
from django.db import models

STATUS_CHOICES = (('New', 'Новая'), ('moderated', 'Модерированная'))


class Quote(models.Model):
    text = models.TextField(max_length=2000, verbose_name='Текст')
    author = models.CharField(max_length=100, verbose_name='Автор')
    email = models.EmailField(verbose_name='Email')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    status = models.CharField(max_length=200, verbose_name='Статус',
                              choices=STATUS_CHOICES, default='New')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Созданно')

    @classmethod
    def get_moderated(cls):
        return cls.objects.filter(status='moderated')

    def __str__(self):
        return f'{self.text[:20]}'

    class Meta:
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'
        ordering = ('-created_at',)


class Vote(models.Model):
    session_key = models.CharField(max_length=40, verbose_name='Ключ сессии')
    quote = models.ForeignKey('webapp.Quote', related_name='votes', verbose_name='Цитата', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=((1, 'up'), (-1, 'down')), verbose_name='Рейтинг',)

    def __str__(self):
        return f'{self.quote} | {self.rating}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'
        ordering = ('quote', 'rating')

source/webapp/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import ensure_csrf_cookie


class IndexView(View):
    @method_decorator(ensure_csrf_cookie)
    def get(self, request, *args, **kwargs):
        return render(request, 'quote/index.html')

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container, tab">
            <ul class="menu">
                <li > <a id="home_menu" href="{% url "webapp:index" %}">Home</a></li>
                <li ><a id="add_quote" href="{% url "webapp:index" %}">Add quote</a></li>
                {% if request.user.is_authenticated %}
                    {% block menu %}{% endblock %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">
                        Привет, {{ request.user.get_full_name|default:request.user.username }}
                    </a></li>
                {% endif %}
                {% block auth_menu %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>
                        <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sign Up</a></li>
                    {% endif %}
                {% endblock %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:password_reset_email' %}">Reset Password</a></li>
                {% endif %}
            </ul>
            {% block search %}
                {% if search_form %}
                    <div class="search-form">
                        <form action="{% url 'webapp:index' %}" method="GET">
                            {{ search_form.search }}
                            <input type="submit" value="Найти">
                        </form>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </nav>
    <div class="container">
        {% include 'partial/messages.html' %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>